spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cfjq3dvnnxge.ap-northeast-2.rds.amazonaws.com:3306/member?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(plDde76MscNwKMt9v4A6Rw==)
    password: ENC(OH+qshDPtFh1h1gDdWExzz/t0BlOzVbo)

  jpa:
    hibernate:
      ddl-auto: update

custom:
  server: ENC(w10K+s4EnEwDbAxgBF+dbNEpajaAseXA)
  storage: ENC(ILubO430i175pGOuVoODag==)
  bucket: ENC(oPnco32AvTLYRwP9ScYf+hXyLU2AT5v+)
