custom:
  front:
    #    url: https://baeker.vercel.app
    url: http://localhost:3000

  feign:
    solved: https://solved.1ll.ca/api/solved
    study: http://localhost:8082/api/study

  s3:
    storage: local
    bucket: baeker-local

  redis:
    host: localhost
    pw:

  kafka:
    gateway: bk.1ll.ca
    server: localhost

  jwt:
    secret-key: ENC(+GbV3Ykx/t5XFlaFHBZnXTzsSf9b3YChS2cVPTvCgwQmevtbB1Hfw91VMC/fTizxVssJvYiAMeQICsuoSrH5zNLh/jxJsXq/)

  db:
    url: jdbc:mysql://127.0.0.1:3306/bk__member?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    usr: ENC(MrlF9UZUaHufCgWLRE3ipQ==)
    pw: ENC(dhw6nRBS+50xHhqPVFnZdw==)

  jpa:
    ddl-auto: create



server:
  port: 8081

spring:
  profiles:
    default: dev

  data:
    redis:
      port: 6379
      host: ${custom.redis.host}
      password: ${custom.redis.pw}

  application:
    name: member-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
      client:
        registration:
          kakao:
            clientId: ENC(0HCojoXJI2AP2Y71MdgjJ8uH7iJLBtyBEOtBkTrteQMu46fZXaJRcikg1KQLA4US)
            client-secret: ENC(Wv7Qf1vhum0OG8DS6XF3fvPxWk8mMsd75TdRzcxN3IsFMc2uHjsF50jm7cNHgsFO)
            scope: account_email, profile_nickname, profile_image, openid
            client-name: kakao
            authorization-grant-type: authorization_code
#            redirect-uri: https://bk.1ll.ca/login/oauth2/code/kakao #https://${custom.kafka.gateway}:443/login/oauth2/code/kakao
#            redirect-uri: http://localhost:3000/login #/oauth2/code/kakao
            client-authentication-method: POST

        provider:
          kakao:
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v1/oidc/userinfo
            user-name-attribute: openid
            issuer-uri: https://kauth.kakao.com

  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${custom.db.url}
    username: ${custom.db.usr}
    password: ${custom.db.pw}


  jpa:
    hibernate:
      ddl-auto: ${custom.jpa.ddl-auto}
    properties:
      hibernate:
        format_sql: true
        show_sql: true


  kafka:
    bootstrap-servers: ${custom.kafka.server}:9092
    consumer:
      group-id: member
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      linger:
        ms: 10

cloud:
  aws:
    credentials:
      access-key: ENC(STIByR/5dds/1MwRIrr0M9JR2yx4wX/OzrBusb1TRuM=)
      secret-key: ENC(aUDadAx1wtJza2duGCwYmYJ04lzNi33fjA8fHtde1qyeWrshkvrvdMtIFtLn5jKy1Adj7UmMTPM=)
    s3:
      bucket: ${custom.s3.bucket}
      storage: ${custom.s3.storage}
    region:
      static: ap-northeast-2
    stack:
      auto: false


message:
  topic:
    member: "member"
    study: "study"
    solved-member: "solved-member"

logging.level:
  org.hibernate:
    SQL: debug
    orm.jdbc.bind: trace

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

---

spring:
  config:
    activate:
      on-profile: dev