spring:
  data:
    redis:
      host: localhost
      port: 6379
  config:
    activate:
      on-profile: dev

custom:
  server: localhost
  storage: local
  bucket: baeker-local
  feign:
    study: http://localhost:8082/api/study